project:
  type: book

book:
  title: "Senior Coordinator, Data & GIS Analytics – Technical Assessment"
  author: "Idris"
  date: "July 30th 2026"
  chapters:
    - index.qmd
    - part1_geospatial.qmd
    - part2_survey_or_instrument.qmd
    - part3_coordination.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true

  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true

execute:
  freeze: auto
  warning: false
  message: false

editor: visual
